# NumPy Array Creation

## NumPy vs Python Lists

In [112]:
import numpy as np
import time
import sys

# Test NumPy array performance
start = time.time()
arr = np.array([1,2,3,4,5])
print(arr)
end = time.time()
print("NumPy time:", end-start)
print("Memory taken by array:", arr.nbytes, "bytes")

# Test Python list performance
start = time.time()
b = [1,2,3,4,5]
print(b)
end = time.time()
print("Python list time:", end-start)
print("Memory taken by list:", sys.getsizeof(b), "bytes")

[1 2 3 4 5]
NumPy time: 0.0006258487701416016
Memory taken by array: 40 bytes
[1, 2, 3, 4, 5]
Python list time: 7.009506225585938e-05
Memory taken by list: 104 bytes


## Creating Arrays from Lists

creating numpy array using python list or converting python list to numpy array is same

In [113]:
# Creating numpy array from a list
my_list = [1,2,3,4,5]
# here we are converting a python list to a numpy array
arr = np.array(my_list)
print("Array:", arr)
print("Type:", type(arr))

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [114]:
my_list = [1,2,3,4,5]
# here we are converting a python list to a numpy array using asarray
np_list = np.asarray(my_list)
print(np_list)
print(type(np_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Creating Arrays with Default Values

In [115]:
# np.full - Fill array with default values

# np.full((shape of array),default value)
arr = np.full((2,3), 9)
print("Full array:")
print(arr)

Full array:
[[9 9 9]
 [9 9 9]]


In [116]:
# np.zeros - Create array filled with zeros
arr = np.zeros((2,3), dtype=int)

# np.zeros((shape of array), dtype)
print("Zeros array:")
print(arr)
print("Data type:", arr.dtype)

Zeros array:
[[0 0 0]
 [0 0 0]]
Data type: int64


In [117]:
# np.ones - Create array filled with ones
arr = np.ones((2,3), dtype=int)
# np.ones((shape of array), dtype)
print("Ones array:")
print(arr)
print("Data type:", arr.dtype)

Ones array:
[[1 1 1]
 [1 1 1]]
Data type: int64


creating a empty array:

If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary(random) and have no significance.

In [118]:
# np.empty 
arr = np.empty(4)
# np.empty((shape of array))
print("Empty array:")
print(arr)

Empty array:
[ 0.          3.33333333  6.66666667 10.        ]


## Creating Arrays with Random Values

In [119]:
from numpy import random

# to generate a random integer we use randint
# random.randint(range)
a = random.randint(100) # here 100 is the range so it generate the number from 0 to 100
print("Random int:", a)

Random int: 36


In [120]:
# Random float (0-1)
b = random.rand()
# here it generates a random float number between 0 and 1
print("Random float:", b)

Random float: 0.5706466468309209


In [121]:
# 1D array of random integers
# random.randint(range, size)
# here it generates an array of 5 random integers between 0 and 100
c = random.randint(100, size=5) 
print("1D random array:", c)

1D random array: [25 77 85 85 56]


In [122]:
# 2D array of random integers
# random.randint(range, size=(rows, columns))
# here it generates a 2D array of shape 3x5 with random integers between
d = random.randint(100, size=(3,5))
print("2D random array:")
print(d)

2D random array:
[[99 17 47 33 24]
 [50 35 62 17 55]
 [37  6 57 19 40]]


In [123]:
# here we are generating random floats in a 1D array of size 5
e = random.rand(5)
print("1D random floats:", e)

1D random floats: [0.40089042 0.16787516 0.92643393 0.925897   0.01477539]


In [124]:
# here we are generating random floats in a 2D array of shape 3x5
f = random.rand(3,5)

print("2D random floats:")
print(f)

2D random floats:
[[0.11616492 0.59759619 0.6604192  0.52292625 0.22918107]
 [0.49889429 0.17805317 0.57432376 0.14608571 0.6382652 ]
 [0.33786907 0.76615274 0.10380627 0.51830439 0.24740721]]


In [125]:
# Random choice from array
# here it randomly selects one element from the given list for that we will use random.choice
g = random.choice([3,4,56,7])
print("Random choice:", g)

Random choice: 4


In [126]:
# Multiple random choices
# here it generates an array with the values given by us with the shape 
h = random.choice([3,4,5,6,7], size=(3,5))
print("Multiple choices:")
print(h)

Multiple choices:
[[4 5 6 3 5]
 [6 3 4 3 4]
 [5 4 5 6 6]]


## Creating Arrays with Sequences

In [127]:
# np.arange - Similar to Python range
# np.arange(start, stop, step)
arr = np.arange(0, 10, 2)
print("Arange:", arr)

Arange: [0 2 4 6 8]


In [128]:
# np.linspace - Evenly spaced values
# np.linspace(start, stop, number of values)
arr = np.linspace(0, 10, 4)
print("Linspace:", arr)

Linspace: [ 0.          3.33333333  6.66666667 10.        ]


# Inserting Element Into Array

In [129]:
# here we are creating a new array by inserting a new value to the existing array using np.append
arr_1d = np.array([1, 2, 3])
arr_1d = np.append(arr_1d, 4)
print(arr_1d)

[1 2 3 4]


In [130]:
# here we are inserting the value 10 at index 1
arr_1d = np.array([1, 2, 3])
arr_1d = np.insert(arr_1d, 1, 10) 
print(arr_1d)

[ 1 10  2  3]


axis = 0 -----> row
axis = 1 ------> column

In [131]:
# 2D array

# her we are appending a new row to the existing row by using np.append with axis=0 


arr_2d = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
# Specify axis=0 to append along the row axis
arr_2d = np.append(arr_2d, new_row, axis=0)
print(arr_2d)

[[1 2]
 [3 4]
 [5 6]]
