# NumPy Array Creation

## NumPy vs Python Lists

In [14]:
import numpy as np
import time
import sys

# Test NumPy array performance
start = time.time()
arr = np.array([1,2,3,4,5])
print(arr)
end = time.time()
print("NumPy time:", end-start)
print("Memory taken by array:", arr.nbytes, "bytes")

# Test Python list performance
start = time.time()
b = [1,2,3,4,5]
print(b)
end = time.time()
print("Python list time:", end-start)
print("Memory taken by list:", sys.getsizeof(b), "bytes")

[1 2 3 4 5]
NumPy time: 0.0008680820465087891
Memory taken by array: 40 bytes
[1, 2, 3, 4, 5]
Python list time: 6.389617919921875e-05
Memory taken by list: 120 bytes


## Creating Arrays from Lists

creating numpy array using python list or converting python list to numpy array is same

In [15]:
# Creating numpy array from a list
my_list = [1,2,3,4,5]
# here we are converting a python list to a numpy array
arr = np.array(my_list)
print("Array:", arr)
print("Type:", type(arr))

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [16]:
my_list = [1,2,3,4,5]
# here we are converting a python list to a numpy array using asarray
np_list = np.asarray(my_list)
print(np_list)
print(type(np_list))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Creating Arrays with Default Values

In [26]:
# np.full - Fill array with default values

# np.full((shape of array),default value)
arr = np.full((2,3), 9)
print("Full array:")
print(arr)

Full array:
[[9 9 9]
 [9 9 9]]


In [27]:
# np.zeros - Create array filled with zeros
arr = np.zeros((2,3), dtype=int)

# np.zeros((shape of array), dtype)
print("Zeros array:")
print(arr)
print("Data type:", arr.dtype)

Zeros array:
[[0 0 0]
 [0 0 0]]
Data type: int64


In [28]:
# np.ones - Create array filled with ones
arr = np.ones((2,3), dtype=int)
# np.ones((shape of array), dtype)
print("Ones array:")
print(arr)
print("Data type:", arr.dtype)

Ones array:
[[1 1 1]
 [1 1 1]]
Data type: int64


creating a empty array:

If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary(random) and have no significance.

In [35]:
# np.empty 
arr = np.empty(4)
# np.empty((shape of array))
print("Empty array:")
print(arr)

Empty array:
[ 0.          3.33333333  6.66666667 10.        ]


## Creating Arrays with Random Values

In [21]:
from numpy import random

# to generate a random integer we use randint
# random.randint(range)
a = random.randint(100) # here 100 is the range so it generate the number from 0 to 100
print("Random int:", a)

# Random float (0-1)
b = random.rand()
# here it generates a random float number between 0 and 1
print("Random float:", b)

# 1D array of random integers
# random.randint(range, size)
# here it generates an array of 5 random integers between 0 and 100
c = random.randint(100, size=5) 
print("1D random array:", c)

# 2D array of random integers
# random.randint(range, size=(rows, columns))
# here it generates a 2D array of shape 3x5 with random integers between
d = random.randint(100, size=(3,5))
print("2D random array:")
print(d)

Random int: 15
Random float: 0.3220795334765012
1D random array: [12  8 78 86  9]
2D random array:
[[38 62 10 35 68]
 [87 11 35 94 92]
 [98 23  4 59 96]]


In [22]:
# Random floats
e = random.rand(5)
print("1D random floats:", e)

# 2D random floats
f = random.rand(3,5)

print("2D random floats:")
print(f)

1D random floats: [0.64830905 0.21778303 0.49646787 0.82416338 0.98186276]
2D random floats:
[[0.86259814 0.68275467 0.19470501 0.20240828 0.44279458]
 [0.5840473  0.93712805 0.92123101 0.35406796 0.02006133]
 [0.96996209 0.78908537 0.70413284 0.50468577 0.75878936]]


In [23]:
# Random choice from array
# here it randomly selects one element from the given list
g = random.choice([3,4,56,7])
print("Random choice:", g)

# Multiple random choices
# here it generates an array with the values given by us with the shape 
h = random.choice([3,4,5,6,7], size=(3,5))
print("Multiple choices:")
print(h)

Random choice: 56
Multiple choices:
[[3 5 3 7 4]
 [4 6 3 4 4]
 [7 3 3 4 4]]


## Creating Arrays with Sequences

In [33]:
# np.arange - Similar to Python range
# np.arange(start, stop, step)
arr = np.arange(0, 10, 2)
print("Arange:", arr)

Arange: [0 2 4 6 8]


In [34]:
# np.linspace - Evenly spaced values
# np.linspace(start, stop, number of values)
arr = np.linspace(0, 10, 4)
print("Linspace:", arr)

Linspace: [ 0.          3.33333333  6.66666667 10.        ]
