In [22]:
import numpy as np

# Copy vs View

Copy:
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

View:
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



Copy

to copy the data from another array we will use array_created_by_us.copy()    function

In [23]:

arr = np.array([1,2,3,4,5])
x = arr.copy()
#after copying of arr to x we can add an element to arr but the element won't come in x
arr[0] = 9
print(arr)
print(x)
print('\n')


[9 2 3 4 5]
[1 2 3 4 5]




In [24]:
# checking whether x is a view or a copy
print(x.base)
 # if the array was created by using using copy it gives none in output

None


View 

To view the data from another array we will use array_created_by_us.view()  function

Using a View saves memory because it doesn't create a new array

In [25]:
#when we use  .view the element which was added to arr also comes to x
x = arr.view()
arr[0] = 9
print(arr)
print(x)

[9 2 3 4 5]
[9 2 3 4 5]


In [26]:
# checking whether x is a view or a copy
print(x.base)
 # if the array was created by using using view it gives original array in output

[9 2 3 4 5]


# NaN Handling

NaN stands for not a number
it is a float values for missing values

In [27]:
# here we are a an array with NaN values and we will see how to handle them
arr = np.array([1, 2, np.nan, 4])
print(arr)

[ 1.  2. nan  4.]


In [28]:
# checking for Nan values in an array if there is a NaN value in an array it gives True in the output else False
# for that we will use np.isnan() function
np.isnan(arr)

array([False, False,  True, False])

In [29]:
# Filtering out NaN values from the array
# for this we will use ~np.isnan() function
# so it gives non Nan values 
filtered_arr = arr[~np.isnan(arr)]
print(filtered_arr)

[1. 2. 4.]


In [30]:
# counting number of NaN values
# here we are sum function also because it add all the NaN values in an array
num_nan = np.isnan(arr).sum()
print(num_nan)

1


In [31]:
# Example
arr = np.array([1, 2, np.nan, 4, np.nan,6])
num_nan = np.isnan(arr).sum()
print(num_nan)

2


In [32]:
# replacing Nan values with some other values 
# np.nan_to_num(array want to replace NaN values, nan=value we want to replace) 
arr = np.array([1, 2, np.nan, 4, np.nan,6])
x = nan_to_num = np.nan_to_num(arr, nan=0)
print(x)
# so if we see the output all the Nan Values are replaced with 0

[1. 2. 0. 4. 0. 6.]


Aggregation(forming a number) that ignore naN values



In [35]:
# here these values ignore naN values and continues with other values
print(np.nanmean(arr))
print(np.nansum(arr))
print(np.nanmax(arr))
print(np.nanmedian(arr))

3.25
13.0
6.0
3.0


In [34]:
# creating 2D array with NaN values
data = np.array([[1, np.nan],
                 [3, 4]])

data
# same operations can be performed on 2D arrays as well which we have done with 1D array

array([[ 1., nan],
       [ 3.,  4.]])