In [4]:
import numpy as np

In [6]:

arr = np.array([1,2,3,4,5])
x = arr.copy()
#after copying of arr to x we can add an element to arr but the element won't come in x
#arr[0] = 9
print(arr)
print(x)
print('\n')
#when we use  .view the element which was added to arr also comes to x
x = arr.view()
arr[0] = 9
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


[9 2 3 4 5]
[9 2 3 4 5]
