# Array Dimensions and Properties

In [1]:
import numpy as np

## 0D Array (Scalar)

In [2]:
#0 dimension array
arr = np.array(42)
print(arr)

42


In [3]:
# here we can set the data type of an array otherwise numpy gives int values in output
arr = np.array(42,dtype = float)
print(arr)

42.0


## 1D Array

In [4]:
# 1 dimenssion array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
# here we can set the data type of an array otherwise numpy gives int values in output
arr = np.array([1,2,3,4,5],dtype = float)
print(arr)

[1. 2. 3. 4. 5.]


## 2D Array

In [6]:
# 2 dimension
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# here we can set the data type of an array otherwise numpy gives int values in output
arr = np.array([[1,2,3],[4,5,6]],dtype = float)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


## 3D Array

In [8]:
# 3 dimension
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# here we can set the data type of an array otherwise numpy gives int values in output
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype = float)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Check Number of Dimensions (ndim)

In [10]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3],[4,5,6]])

print("0D ndim:", a.ndim)
print("1D ndim:", b.ndim)
print("2D ndim:", c.ndim)

0D ndim: 0
1D ndim: 1
2D ndim: 2


## Creating Array with Specified Dimensions

In [11]:
# creating an array using n no of dimensions by taking user input from user
n = int(input("enter a number to create no of dimensions: "))
arr = np.array([1,2,3,4], ndmin = n)
print(arr)
print('number of dimensions : ', arr.ndim)

[[[1 2 3 4]]]
number of dimensions :  3


## Array Shape

In [12]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("Array:")
print(arr)
print("\nShape:", arr.shape)
print("Meaning: 2 rows, 4 columns")

Array:
[[1 2 3 4]
 [5 6 7 8]]

Shape: (2, 4)
Meaning: 2 rows, 4 columns


In [13]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("shape of array:", arr.shape)


[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


here the shape is (1,1,1,1,4) because we have created an array with 5 dimensions if you observe each dimension at lat least it gave 4 because the nof of elements in array are 4
so the last dimension contains 4 elements and rest all contains 1

In [14]:
# another example
n = int(input("enter no of dimensions: "))
arr = np.array([1,2,3,4,5,6], ndmin = n)
print(arr)
print("shape of array:", arr.shape)

[[[1 2 3 4 5 6]]]
shape of array: (1, 1, 6)
