# Reshaping Arrays

In [2]:
import numpy as np

## Basic Reshape Operations

In [3]:
# 1D to 2D
arr = np.array([1,2,3,4,5,6,7,8])
print("Original 1D array:")
print(arr)

newarr = arr.reshape(4, 2)
print("\nReshaped to 4x2:")
print(newarr)

Original 1D array:
[1 2 3 4 5 6 7 8]

Reshaped to 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
# 1D to 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2, 3, 2)
# arr.reshape(2,3,2) means we want to reshape the array into 2 blocks, each containing 3 rows and 2 columns.
# arr.reshape(rows,columns,blocks)
print("\nReshaped to 2x3x2:")
print(newarr)


Reshaped to 2x3x2:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
newarr = arr.reshape(2,3,-1) 
# here first it checks the size of the array. here the size of array is 12 
# then it checks the given dimensions 2 and 3 multiply it 2*3=6
# then it divides the size of array with 6 i.e 12/6=2
# so the new shape will be (2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
newarr = arr.reshape(1,3,-1) 
# here first it checks the size of the array. here the size of array is 12 
# then it checks the given dimensions 3 and 3 multiply it 3*3=9
# then it divides the size of array with 9 i.e 12/9=1.33 (which is not an integer, so this reshape will raise an error)
# so the new shape will be (3,3,?)
print(newarr)

print(newarr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)


## Flattening Arrays

In [12]:
# Flattening array means converting a multidimensional array into a 1D array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:")
print(arr)
# if we use -1 it automatically calculates dimension based on it it directly
newarr = arr.reshape(-1)
print("\nFlattened:")
print(newarr)

2D array:
[[1 2 3 4]
 [5 6 7 8]]

Flattened:
[1 2 3 4 5 6 7 8]


In [8]:
# Different flattening methods
a = np.array([[1, 2], [3, 4]])

print("reshape(-1):", a.reshape(-1))   # Same as flattening
print("ravel():", a.ravel())          # Flattens without copy if possible
print("flatten():", a.flatten())    # Always returns a copy
print("\nDifference: ravel may not copy, flatten always copies")

reshape(-1): [1 2 3 4]
ravel(): [1 2 3 4]
flatten(): [1 2 3 4]

Difference: ravel may not copy, flatten always copies


In [26]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.reshape(-1))
# Flatten(converts multidimensional array into 1Dimensional array)


[1 2 3 4 5 6]


## Using -1 for Auto Dimension

In [9]:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2, 3, -1)
# here first it checks the size of the array. here the size of array is 12 
# then it checks the given dimensions 2 and 3 multiply it 2*3=6
# then it divides the size of array with 6 i.e 12/6=2
# so the new shape will be (2,3,2)
print(newarr)
print("Shape:", newarr.shape)

Using -1 for auto dimension:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Shape: (2, 3, 2)


In [17]:
# here first we are creating an array with a range 8 that means the array contains 0-7 elements and the we are reshaping to 2x2x2
arr = np.array(range(8))
# arr.reshape(rows,columns,blocks)
print(arr.reshape(2,2,2))


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
# here first it checks the size of the array. here the size of array is 8 
# then it checks the given rows given by the user hwew we have given 4 rows 
# then it divides the size of array with 4 i.e 8/4=2
# so the new shape will be (4,2)
print(arr.reshape(4,-1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [24]:
print(arr.reshape(-1,2))
# here first it checks the size of the array. here the size of array is 8 
# then it checks the given columns given by the user here we have given 2 columns 
# then it divides the size of array with 2 i.e 8/2=4
# so the new shape will be (4,2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


## Column Vector Creation

In [36]:
a = np.array([1, 2, 3, 4])
# here first it checks the size of the array. here the size of array is 4 
# then it checks the given columns given by the user here we have given 2 columns 
# then it divides the size of array with 2 i.e 4/2=2
# so the new shape will be (2,2)
column_vector = a.reshape(-1, 2)
print("Original array:", a)
print("\nAs column vector:")
print(column_vector)

Original array: [1 2 3 4]

As column vector:
[[1 2]
 [3 4]]


## Reshape with Order

There are three orders C,F,A
C is default order

In [40]:
# Reshape with C order (row-major, default)
a = np.array([1, 2, 3, 4])
b = a.reshape((2, 2))
print("Default order (C):")
print(b)
# the first row is filled completely before moving to the next row. 
# this is the order
#[[1-->2]]
#      |
#      v
# <-----
# |
# v
#[[3-->4]]

Default order (C):
[[1 2]
 [3 4]]


In [ ]:
# Reshape with F order (column-major, Fortran)
c = a.reshape((2, 2), order='F')
print("\nFortran order (F):")
print(c)
# first column is filled completely before moving to the next column. 
# this is the order
#[[1    -->  3]]
#  |   |      |
#  v   |      |
#   -->|      |
# [[2         --> 4]]


Fortran order (F):
[[1 3]
 [2 4]]


In [ ]:
c = a.reshape((2, 2), order='A')
print("\nAny/Automatic order (A):")
print(c)
# the order matches the memory layout of the underlying array if it is Fortran contiguous in memory; otherwise, it uses C-like order. 


Any/Automatic order (A):
[[1 2]
 [3 4]]
