# Data Types and Type Conversion

In [2]:
import numpy as np

## Checking Data Types

In [3]:
arr = np.array([1,2,3,4])
fruits = np.array(["apple","banana","mango"])

print("Integer array dtype:", arr.dtype)
print("String array dtype:", fruits.dtype)

Integer array dtype: int64
String array dtype: <U6


## Specifying Data Type at Creation

In [4]:
# Create array as string
# here 'S' denotes string datatype
# here when we are creating an array we are defining the data type as string 
arr = np.array([1,2,3,4], dtype='S')
print("String dtype array:")
print(arr)
print("dtype:", arr.dtype)

# Create array as 32-bit integer
x = np.array([1,2,3,4], dtype="i4")
print("\n32-bit int array:")
print(x)
print("dtype:", x.dtype)

String dtype array:
[b'1' b'2' b'3' b'4']
dtype: |S1

32-bit int array:
[1 2 3 4]
dtype: int32


## Type Conversion with astype()

In [5]:
# Convert float to integer
arr = np.array([1.2, 3.4, 5.6])
print("Original array:", arr)
print("Original dtype:", arr.dtype)
# astype() function creates a copy of the array,and allows you to specify the data type as a parameter.
# it first creates an array arr with float values and then converts it to an integer type, stores the result in newarr. It then prints both the new array and its data type.
newarr = arr.astype("i")  # Convert to integer
print("\nConverted to int:")
print(newarr)
print("New dtype:", newarr.dtype)

Original array: [1.2 3.4 5.6]
Original dtype: float64

Converted to int:
[1 3 5]
New dtype: int32


In [6]:
# Another example
x = np.array([1.2, 3.4, 5.4])
print("Original:", x)

y = x.astype("int")
print("\nConverted:")
print(y)
print("New dtype:", y.dtype)

Original: [1.2 3.4 5.4]

Converted:
[1 3 5]
New dtype: int64


## Boolean Conversion
1. Any non-zero value (positive value or negative value ) becomes True.
2. The value 0 becomes False.

In [8]:
# Convert to boolean
# Rule: 0 becomes False, non-zero becomes True
arr = np.array([-1,0,1,10,2])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True  True]
bool
