# Indexing and Slicing

In [2]:
import numpy as np

## 1D Array Indexing

In [3]:
arr = np.array([1,2,3,4])
print("Array:", arr)
print("First element:", arr[0])
print("Second element:", arr[1])
print("Sum of arr[1] and arr[2]:", arr[1] + arr[2])

Array: [1 2 3 4]
First element: 1
Second element: 2
Sum of arr[1] and arr[2]: 5


## 2D Array Indexing

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array:")
print(arr)
#print(arr[row number , index of element in row])
print("\nElement at [0,0]:", arr[0,0])
print("Element at [0,1]:", arr[0,1])
print("Element at [1,2]:", arr[1,2])

Array:
[[1 2 3]
 [4 5 6]]

Element at [0,0]: 1
Element at [0,1]: 2
Element at [1,2]: 6


## Accessing Element From an Array

In [5]:
# here first we are creating an array with a range 16 that means the array contains 0-15 elements 
a = np.arange(16)
# then we are reshaping to 4x4
b = a.reshape(4, 4)
print(a)
print('\n')
print(b)
print('\n')
#here [2][1] means 2 row, 1 column so according to given input [8 9 10 11]
print(b[2][1]) 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


9


In [6]:
print(b[2, 1])  # Alternative way to access the same element
#print(b[row,column])

9


In [7]:
# it is mainly used when we want to access a particular element in a multidimensional array
print(b[3,1])
#print(b[row,column])

13


## 1D Array Slicing

In [8]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[-4:-1])
print(arr[:4])#here the array gives first 4 elements
print(arr[4:])# here the array gives elements after index 4
#print(arr[start:end:step])
#step: suppose here if i have given 2 so it prints every second element from start to end
print(arr[1:5:2])
#:: same as step but here we dont use start and end here i have given 3 so it prints every third element
print(arr[::3])

[2 3 4 5]
[4 5 6]
[1 2 3 4]
[5 6 7]
[2 4]
[1 4 7]


In [9]:
# Slicing with step
arr = np.array([1,2,3,4,5,6,7])
print("Array:", arr)
print("\nSlicing with step:")
print("arr[1:5:2] (step=2):", arr[1:5:2])
print("arr[::3] (every 3rd element):", arr[::3])

Array: [1 2 3 4 5 6 7]

Slicing with step:
arr[1:5:2] (step=2): [2 4]
arr[::3] (every 3rd element): [1 4 7]


## 2D Array Slicing

In [10]:
#2d slicing
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,1:4])
#From both elements, return index 2:
print(arr[0:2,2])
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
