# Array Iteration

In [17]:
import numpy as np

## 1D Array Iteration

In [18]:
arr = np.array([1,2,3,4])
print("Array:", arr)

for x in arr:
    print(x)

Array: [1 2 3 4]
1
2
3
4


## 2D Array Iteration

In [19]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("2D Array:")
print(arr)
print("\nIterating rows only:")
for x in arr:
    print(x)

2D Array:
[[1 2 3 4]
 [5 6 7 8]]

Iterating rows only:
[1 2 3 4]
[5 6 7 8]


In [ ]:
# instead of using nested loops
# it is alernative method for looping through each element in the array. it does not care about the number of dimensions in arrray and shape of array
# by using flat attribute

for z in arr.flat: 
    print(z)

In [37]:
# here we are Iterating to get individual elements from an array

arr = np.array([[1,2,3,4], [5,6,7,8]])
print("Getting individual elements:")
# here x iterate throught the rows from the given array
# and y iterate through the individual elements of the row which x iterated 
# so first it prints all elements of first row then moves to second row

for x in arr:
    for y in x:
        print(y)

Getting individual elements:
1
2
3
4
5
6
7
8


In [ ]:
# instead of using nested loops
# it is alernative method for looping through each element in the array. it does not care about the number of dimensions in arrray and shape of array
# by using the flat attribute

for z in arr.flat:
     print(z)

1
2
3
4
5
6
7
8


## 3D Array Iteration

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print("3D Array iteration (2D blocks):")
for x in arr:
    print(x)
    print("---")


3
3D Array iteration (2D blocks):
[[1 2 3]
 [4 5 6]]
---
[[ 7  8  9]
 [10 11 12]]
---


In [ ]:
# Get individual elements
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array iteration (individual elements):")
for x in arr:
    for y in x:
        for z in y:
            print(z)

3D Array iteration (individual elements):


In [ ]:
# instead of using nested loops
# it is alernative method for looping through each element in the array. it does not care about the number of dimensions in arrray and shape of array
# by using flat attribute

for z in arr.flat: 
    print(z)

1
2
3
4
5
6
7
8


## Using nditer() for Efficient Iteration

while using for loops, iterating through each element of an array we need to use more number of for loops which can be difficult to write for arrays with very high dimensionality.
so we use nditer


In [ ]:
# nditer - for high-dimensional arrays without nested loops
arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print("Using nditer:")
for x in np.nditer(arr):
    print(x)

Using nditer:
1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
# nditer with different data type

arr = np.array([1,2,3])
print("nditer with string conversion:")
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)
# it first creates an array arr with float values and then converts it to an integer type, stores the result in newarr. It then prints both the new array and its data type.
# if you wanted to become a data analyst you can ignore this 

nditer with string conversion:
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [45]:
#Iterating through every element of the 2D array by skipping every 2nd element:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("nditer with step (every 2nd element):")
for x in np.nditer(arr[:, ::2]):
    print(x)

nditer with step (every 2nd element):
1
3
5
7


## Using ndenumerate() for Index and Value

In [47]:
# 1D array with indices
arr = np.array([10, 20, 30])
print("1D array with ndenumerate:")
for idx, val in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {val}")

1D array with ndenumerate:
Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30


In [ ]:
# 2D array with indices
arr = np.array([[1, 2], [3, 4]])
print("2D array with ndenumerate:")
for idx, val in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {val}")

2D array with ndenumerate:
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4


Modifying elements in the array with condition. it is most useful fot the persons who wants to get into data roles

In [ ]:
# Modifying elements in the array with condition
arr = np.array([[5, 10], [15, 20]])
print("Original array:")
print(arr)

# Set values > 10 to 0
for idx, val in np.ndenumerate(arr):
    if val > 10:
        arr[idx] = 0

print("\nModified array:")
print(arr)

Original array:
[[ 5 10]
 [15 20]]

Modified array:
[[ 5 10]
 [ 0  0]]
