# Array Iteration

In [2]:
import numpy as np

## 1D Array Iteration

In [3]:
arr = np.array([1,2,3,4])
print("Array:", arr)

for x in arr:
    print(x)

Array: [1 2 3 4]
1
2
3
4


## 2D Array Iteration

In [4]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("2D Array:")
print(arr)
print("\nIterating rows only:")
for x in arr:
    print(x)

2D Array:
[[1 2 3 4]
 [5 6 7 8]]

Iterating rows only:
[1 2 3 4]
[5 6 7 8]


In [5]:
# Iterate to get individual elements
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("Getting individual elements:")
for x in arr:
    for y in x:
        print(y)

Getting individual elements:
1
2
3
4
5
6
7
8


## 3D Array Iteration

In [6]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array iteration (2D blocks):")
for x in arr:
    print(x)
    print("---")

3D Array iteration (2D blocks):
[[1 2 3]
 [4 5 6]]
---
[[ 7  8  9]
 [10 11 12]]
---


In [7]:
# Get individual elements
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3D Array iteration (individual elements):")
for x in arr:
    for y in x:
        for z in y:
            print(z)

3D Array iteration (individual elements):
1
2
3
4
5
6
7
8
9
10
11
12


## Using nditer() for Efficient Iteration

In [8]:
# nditer - for high-dimensional arrays without nested loops
arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print("Using nditer:")
for x in np.nditer(arr):
    print(x)

Using nditer:
1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
# nditer with different data type
arr = np.array([1,2,3])
print("nditer with string conversion:")
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

nditer with string conversion:
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [10]:
# nditer with slicing
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("nditer with step (every 2nd element):")
for x in np.nditer(arr[:, ::2]):
    print(x)

nditer with step (every 2nd element):
1
3
5
7


## Using ndenumerate() for Index and Value

In [11]:
# 1D array with indices
arr = np.array([10, 20, 30])
print("1D array with ndenumerate:")
for idx, val in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {val}")

1D array with ndenumerate:
Index: (0,), Value: 10
Index: (1,), Value: 20
Index: (2,), Value: 30


In [12]:
# 2D array with indices
arr = np.array([[1, 2], [3, 4]])
print("2D array with ndenumerate:")
for idx, val in np.ndenumerate(arr):
    print(f"Index: {idx}, Value: {val}")

2D array with ndenumerate:
Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (1, 0), Value: 3
Index: (1, 1), Value: 4


In [13]:
# Modify elements with condition
arr = np.array([[5, 10], [15, 20]])
print("Original array:")
print(arr)

# Set values > 10 to 0
for idx, val in np.ndenumerate(arr):
    if val > 10:
        arr[idx] = 0

print("\nModified array:")
print(arr)

Original array:
[[ 5 10]
 [15 20]]

Modified array:
[[ 5 10]
 [ 0  0]]
