# Joining and Splitting Arrays

In [1]:
import numpy as np

## Joining Arrays

### 1D Arrays with concatenate()

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print("1D concatenation:")
print(arr)

1D concatenation:
[1 2 3 4 5 6]


### 2D Arrays with concatenate()
axis = 0 --> rows <br>
axis = 1 --> columns

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

# Along rows (default, axis=0)
arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenate along axis=0 (rows):")
print(arr)

Concatenate along axis=0 (rows):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
# Along columns (axis=1)
arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenate along axis=1 (columns):")
print(arr)

Concatenate along axis=1 (columns):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Stack Functions

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

# vstack - stack along rows (vertically)
print("vstack():")
print(np.vstack((arr1, arr2)))

# hstack - stack along columns (horizontally)
print("\nhstack():")
print(np.hstack((arr1, arr2)))

# dstack - stack along depth
print("\ndstack():")
print(np.dstack((arr1, arr2)))

vstack():
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

hstack():
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

dstack():
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## Splitting Arrays

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(np.split(arr, 3))



[array([10, 20]), array([30, 40]), array([50, 60])]


In [19]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
            #   0 1 2 3 4 5 6 7 8 9
# here we are splitting the array values before index 1 and after index 1 and before index 4 and after index 4
print(np.split(arr, [1, 4]))


[array([0]), array([1, 2, 3]), array([4, 5, 6, 7, 8, 9])]


### array_split()
array_split method is used to split the array into different parts

In [ ]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
# here the array will be splitted into 3 parts because we have given 3 as argument
# here not only three it will adjust according to the number given by us
print(newarr)


[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
# here we are printing different parts of array after splitting them
print("Access individual parts:")
print("Part 0:", newarr[0]) 
print("Part 1:", newarr[1])
print("Part 2:", newarr[2])

Access individual parts:
Part 0: [1 2]
Part 1: [3 4]
Part 2: [5 6]


In [33]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 10)
# when we are splitting array into different parts if the number of parts is more than the elements in array then some parts will be empty
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

np.array_split(arr, 2, axis=0) 
# here we are splitting 2D array into 2 parts along rows
#  axis = 0 is default value if we did not provide any axis value it will consider axis=0

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [43]:
np.array_split(arr, 2, axis=1) 
# here we are splitting 2D array into 2 parts along columns

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [7]:
# 2D array split
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print("2D split along axis=1:")
print(newarr)

2D split along axis=1:
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=0)
print("2D split along axis=0:")
print(newarr)
# axis = 0 is default value if we did not provide any axis value it will consider axis=0

2D split along axis=0:
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


### hsplit(), vsplit(), dsplit()

In [46]:
# hsplit - horizontal split
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
newarr = np.hsplit(arr, 2)
print("hsplit:")
print(newarr)

# vsplit - vertical split
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
newarr = np.vsplit(arr, 2)
print("\nvsplit:")
print(newarr)

# dsplit - depth split (3D)
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
newarr = np.dsplit(arr, 2)
print("\ndsplit:")
print(newarr)

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

dsplit:
[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


# Broadcasting

It is a powerful mechanism that allsows arthematics operations between two arrays of different shapes by automatically stretching smaller array to much larger larger array

No loops                
Fast                        
operations happens element wise

Rules for broadcasting :
the shapes of the arrays must be equal or one for them must 1       


In [8]:
# in the simplest case, the two arrays must have exactly the same shape, as in the following example:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
print(a * b)

[2. 4. 6.]


In [9]:
# the simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

a = np.array([1.0, 2.0, 3.0])
b = 2.0 
# here b is scalar value
# though b is scalar value it is treated as the same size of a
# so the b is treated as [2.0,2.0,2.0]
print(a * b)

[2. 4. 6.]



![alt text](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In the simplest example of broadcasting, the scalar b is stretched to become an array of same shape as a so the shapes are compatible for element-by-element multiplication.

In [ ]:
# An example of broadcasting when a 1-d array is added to a 2-d array:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

# A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

![alt text](https://numpy.org/doc/stable/_images/broadcasting_2.png)

In [12]:
# here is the example if the rows are unequal 
array([[  1.,   2.,   3.],
        [11.,  12.,  13.],
        [21.,  22.,  23.],
        [31.,  32.,  33.]])
b = np.array([1.0, 2.0, 3.0, 4.0])
a + b
# if we run this code it will give error because the number of rows are unequal

NameError: name 'array' is not defined

![alt text](https://numpy.org/doc/stable/_images/broadcasting_3.png)