# Linear Algebra - Matrix Operations

## These topics are not essential for Data Analysts


In [83]:
import numpy as np

Numpy Matrix Library

it is used for manipulating matrices, matrix operations, including matrix multiplication, inversion, and decomposition, Eigenvalues,Eigenvectors

Matrix operations:
before getting into this topic revise how to find the det, inverse,adjoint, dot product, vector product, matrix multiplication

## Creating Matrices

In [84]:
# Creating a matrix from string
matrix_str = np.matrix('1 2; 3 4')
print("Matrix from string:")
print(matrix_str)

Matrix from string:
[[1 2]
 [3 4]]


In [85]:
matrix_str = np.matrix('1 2; 3 4; 5 6')
print(matrix_str)

[[1 2]
 [3 4]
 [5 6]]


In [86]:
# Creating a matrix from array
array_data = np.array([[1, 2], [3, 4]])
# here first we have created an array and converted into numpy matrix by using function np.matrix
matrix_from_array = np.matrix(array_data)
print("\nMatrix from array:")
print(matrix_from_array)


Matrix from array:
[[1 2]
 [3 4]]


In [87]:
print(type(array_data))

<class 'numpy.ndarray'>


In [88]:
print(type(matrix_from_array)) # datatype of matrix

<class 'numpy.matrix'>


In [89]:
# Using asmatrix()
array_data = np.array([[5, 6], [7, 8]])
matrix_data = np.asmatrix(array_data)
print("Matrix via asmatrix:")
print(matrix_data)
print("Type array:", type(array_data))
print("Type matrix:", type(matrix_data))

Matrix via asmatrix:
[[5 6]
 [7 8]]
Type array: <class 'numpy.ndarray'>
Type matrix: <class 'numpy.matrix'>


## Matrix Addition 

In [90]:
# Addition of matrices. we can add matrices in two different ways by using + operator and add() function
# Adding two matrices using the + operator
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B

print(C)

[[ 6  8]
 [10 12]]


In [91]:
# Adding two matrices using add() function
c = np.add(A,B)
print(c)

[[ 6  8]
 [10 12]]


# Matrix Subtraction

In [92]:
# subtraction of two matrices. we can subtract matrices in two different ways by using - operator and subtract() function
# Subtracting two matrices using the - operator
A = np.array([[5, 8], [7, 10]])
B = np.array([[2, 4], [3, 6]])
C = A - B
print(C)

[[3 4]
 [4 4]]


In [93]:
# subtracting matrix using subtract() function
c = np.subtract(A,B)
print(c)

[[3 4]
 [4 4]]


## Matrix Multiplication

### Dot Product

In [94]:
# Dot product of the two arrays
# by using function dot()
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

[[37 40]
 [85 92]]


In [95]:
# by using function @ operator
dot = a @ b
print(dot)

[[37 40]
 [85 92]]


### Vector Product

In [96]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

# Vector dot product (1*11 + 2*12 + 3*13 + 4*14)
result = np.vdot(a, b)

print(result)

130


### Inner Product

In [97]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

result = np.inner(a, b)
print("Inner product:")
print(result)
# [[ 1*11+2*12, 1*13+2*14]
#   [3*11+4*12, 3*13+4*14]]

Inner product:
[[35 41]
 [81 95]]


In [98]:
# without using matlib function we can directly mix  2-D mixed with 1-D
a = np.array([[1,0],[0,1]])
b = np.array([1,2])

print(a @ b)


[1 2]


In [99]:
print(b @ a)

[1 2]


## Matrix Determinant

In [100]:
# the determinant of the array

a = np.array([[1,2], [3,4]])
print(np.linalg.det(a))
# 1*4-2*3

-2.0000000000000004


In [101]:
# the determinant of the array or matrix 
# the result will be same for both array and matrix

b = np.array([[6,1,1], [4, -2, 5], [2,8,7]])
print(b)
print(np.linalg.det(b))
# 6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


In [102]:
# here i have converted above array into matrix then i found det of a matrix 
# therefore the result will be same for both array and matrix
x = np.asmatrix(b)
print(x)
print(np.linalg.det(x))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0


## Matrix Inverse

In [103]:
A = np.array([[1, 2], [3, 4]])
print("Original Matrix:")
print(A)

A_inv = np.linalg.inv(A)
print("\nInverse Matrix:")
print(A_inv)

Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [104]:
# Verify inverse (A × A_inv = Identity)
identity = np.dot(A, A_inv)
print("A × A_inv:")
print(identity)

# Check if it's identity matrix
is_identity = np.allclose(identity, np.eye(2))
print("\nIs identity matrix?", is_identity)

A × A_inv:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Is identity matrix? True
