*In this File we can explore how to get data from the file*

# Saving Numpy Array File

Here we have crea here are few exated an array when run this array the output array with be saved into files.The output will be saved into files in binary format. This is not useful to data analysts it is given just to get an idea

we will use np.save("filename.npy",name of array created by us) to save the file
extension is .npy

In [40]:
import numpy as np

In [41]:

arr = np.array([10, 20, 30])
np.save("data.npy", arr)


In [42]:
# np.load() is used to load the array from the .npy file
np.load("data.npy")

array([10, 20, 30])

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# here we are finding the index of the elements greater than 5
indices = np.where(arr > 5)
print("Indices where arr > 5:", indices)

# here we are extracting elements greater than 5
filtered_elements = arr[indices]
print("Elements greater than 5:", filtered_elements)
np.save("data1.npy", filtered_elements)

Indices where arr > 5: (array([5, 6, 7, 8, 9]),)
Elements greater than 5: [ 6  7  8  9 10]


In [44]:
np.load("data1.npy")

array([ 6,  7,  8,  9, 10])

 we will use genfromtxt() function  to read the data from the file.

 we have given data in the data.txt file

 if we observe the data.txt file our data file contains int values but we will get output in float values because the default dtype for genfromtxt is float

 when we are reading the data from the file we need to specify the delimiter also.

delimiter: Specifies the character used to separate values (default is whitespace, so you need to set it to ',' for CSV)


In [45]:

filedata = np.genfromtxt('data.txt',delimiter=',')

print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [46]:
# wec an use parameter dtype to specify the data type of the array
filedata = np.genfromtxt('data.txt',delimiter=',',dtype = 'int')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [47]:
# getting th shaape of the file 
filedata.shape

(3, 18)

In [48]:
filedata.dtype

dtype('int64')

In [49]:
# checking the data in file by sing conditions
[filedata>20]

[array([[False, False,  True, False,  True,  True, False, False,  True,
         False, False, False, False, False, False, False, False, False],
        [False,  True, False,  True,  True,  True, False,  True, False,
         False, False, False, False, False, False, False, False, False],
        [False,  True,  True, False,  True, False, False, False,  True,
         False, False, False, False, False, False, False,  True,  True]])]

In [50]:
filedata[filedata>20]

array([ 21, 196,  75,  34,  42,  33, 766,  75,  55,  22,  33, 999,  78,
        76,  88])

In [51]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [52]:
filedata[(filedata > 50) & (filedata < 100)]

array([75, 75, 55, 78, 76, 88])

In [53]:
# getting th shaape of the file 
filedata.shape

(3, 18)

# Data Distribution

In [54]:
"""We can generate random numbers based on defined probabilities ,
using the choice() method of the random module."""
#p is probability here the sum of probability should be equal to 1
from numpy import random
# size papameter is used to specify the shape of the array
arr = random.choice([2,3,4,5],p=[0.3,0.4,0.2,0.1],size=(100))
# here we have given probability from 2 is 30%(0.3),3 is 40%(0.4),4 is 20%(0.2) and 5 is 10%(0.1)
print(arr)
print('\n')

[2 5 3 4 4 3 4 5 4 5 3 3 2 4 4 4 2 2 4 2 5 3 5 3 2 2 4 3 4 2 5 4 4 3 5 2 2
 2 3 5 3 3 3 2 3 2 2 5 3 3 3 2 2 4 2 4 2 3 2 3 3 3 2 3 4 2 3 3 4 2 4 4 2 2
 3 4 4 3 4 2 3 3 3 3 4 4 4 2 4 4 5 2 4 2 3 3 3 3 3 3]




In [55]:
#2D arrays
x = random.choice([2,3,4,5],p=[0.3,0.4,0.2,0.1],size=(3,5))
print(x)

[[5 3 5 3 4]
 [2 2 2 3 3]
 [3 3 3 2 3]]


# Random Permutations(shuffling arrays)

In [56]:
#The shuffle() method makes changes to the original array.
#  to shuffle the values in the array we use shuffle() function
arr = np.array([1,2,3,4])
random.shuffle(arr)
print(random.permutation(arr))

[1 4 3 2]


In [57]:
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).
arr = np.array([1,2,3,4,5])
print(arr)
print(random.permutation(arr))

[1 2 3 4 5]
[4 3 1 2 5]


In [58]:
arr = np.array([10, 20, 30])
perm = np.random.permutation(arr)
print("Original:", arr)
print("Permuted:", perm)

Original: [10 20 30]
Permuted: [30 20 10]


In [59]:
import random
s = "hello"
permuted = ''.join(random.sample(s, len(s)))
print(permuted)

eohll
