# Creating numpy arrays using random module

In [1]:
from numpy import random

In [2]:
a = random.randint(100)
print(a)
print('\n')

35




In [3]:
#generate random number from 0 to 1
b = random.rand()
print(b)

0.14869435619731552


In [4]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
c = random.randint(100,size =(5))
print(c)

[55  1 97 99 35]


In [5]:
#3 rows and 5 columns
d = random.randint(100,size=(3,5))
print(d)

[[17 52 88 33 45]
 [98 14 96 65 94]
 [82 79 14 41 73]]


In [6]:
# to generate floats
e = random.rand(5)
print(e)

[0.4361115  0.06428906 0.36032786 0.2923245  0.11529507]


In [7]:
f = random.rand(3,5)
print(f)

[[0.15656726 0.39765541 0.47442833 0.35201911 0.35553153]
 [0.95845301 0.58696278 0.8225164  0.81116846 0.49521145]
 [0.47725238 0.60264385 0.76219039 0.53378009 0.17206051]]


In [8]:
# generate random number from float
g = random.choice([3,4,56,7])
print(g)

4


In [9]:
h = random.choice([3,4,5,6,7],size=(3,5))
print(h)

[[7 4 4 5 5]
 [7 5 6 3 6]
 [5 4 3 5 5]]


In [10]:
# generates an array of numbers starting from 0 up to (but not including) 10, with a step of 2
arr = np.arange(0,10,2)
print(arr)

NameError: name 'np' is not defined

In [ ]:
# generates an array of 4 evenly spaced numbers over the interval from 0 to 10, inclusive.
arr = np.linspace(0,10,4)
print(arr)