# Basic Statistics

In [1]:
import numpy as np

# Mean

In [2]:
# Here we are calculating the mean of all values in the array
# 1D Array
arr = np.array([2,3,4,5])
print(np.mean(arr))

3.5


In [3]:
# 2D Array 
# calculating the mean of the 2d array 
arr_1 = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr_1)) # here it gives the mean of all values in the array


3.5


In [4]:
print(np.mean(arr_1, axis=0)) # here it gives the mean of each column

[2.5 3.5 4.5]


In [5]:
print(np.mean(arr_1, axis=1)) # here it gives the mean of each row

[2. 5.]


In [6]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well now calulate along the rows and columns
arr_1 = np.array([[1,2,3],[4,5,6],[10,20,30]])
print(np.mean(arr_1)) 

9.0


# Median

In [7]:
# here we are calculating the median of the array 
arr_1 = np.array([1,2,3,4,5,6,7])
print(np.median(arr_1)) 

4.0


In [8]:
# here we are calculating the median of 2D array
arr_1 = np.array([[1,2,3],[4,5,6]])
print(np.median(arr_1)) 

3.5


In [9]:
print(np.median(arr_1, axis=0)) # here it gives the median of each column

[2.5 3.5 4.5]


In [10]:
print(np.median(arr_1, axis=1)) # here it gives the median of each row

[2. 5.]


In [11]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well now calulate along the rows and columns
arr_1 = np.array([[1,2,3],[4,5,6],[10,20,30]])
print(np.median(arr_1)) 

5.0


Note: In data analysis, always check both mean and median. If they are very different, your data has outliers or is skewed.


# Standard Deviation
Measures how spread out data is from the mean. Low std = data is clustered. High std = data is spread out.


In [12]:
# here we are the standard deviation of 1D array
arr = np.array([10, 12, 11, 10, 9, 11, 12, 10])
print(np.std(arr))

0.9921567416492215


In [13]:
# 2D array 
data = np.array([[1, 2, 3], [4, 5, 6]])
print(np.std(data, axis=0)) # Standard deviation along columns

[1.5 1.5 1.5]


In [14]:
print(np.std(data, axis=1)) # Standard deviation along rows

[0.81649658 0.81649658]


In [15]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well  now calulate along the rows and columns
arr_1 = np.array([[1,2,3],[4,5,6],[10,20,30]])
print(np.std(arr_1)) 

9.201449161228174


# Variance
formula for: variance = (standard deviation)^2

In [16]:
# here we are calculating the variance for 1D array for that we are using var function
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print('Variance:', np.var(arr))
print('Std Dev: ', np.std(arr))

print('Verify:  ', np.sqrt(np.var(arr))) # here we are verying that the standard deviation is the square root of variance

Variance: 4.0
Std Dev:  2.0
Verify:   2.0


In [17]:
# calculating the variance and standard deviation for 2D array
data = np.array([[1, 2, 3], [4, 5, 6]])
print('Variance:', np.var(data))
print('Std Dev: ', np.std(data))

print('Verify:  ', np.sqrt(np.var(data)))

Variance: 2.9166666666666665
Std Dev:  1.707825127659933
Verify:   1.707825127659933


In [18]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well  now calulate along the rows and columns
arr_1 = np.array([[1,2,3],[4,5,6],[10,20,30]])
print(np.var(arr_1))

84.66666666666667


# Minimum Value and Maximum Value

In [19]:
# here we are calculating the minimum and maximum value in the 1D array
arr_1 = np.array([1,2,3])
print(np.min(arr_1)) # here it gives the minimum value in the array

1


In [20]:
arr_1 = np.array([1,2,3])
print(np.max(arr_1)) # here it gives the maximum value in the array

3


In [21]:
# 2D array 
data = np.array([[1, 2, 3], [4, 5, 6]])
print(np.min(data)) # Minimum value in the entire array

1


In [22]:
print(np.min(data, axis=0)) # Minimum value along columns
print(np.max(data, axis=0)) # Maximum value along rows  

[1 2 3]
[4 5 6]


In [23]:
print(np.min(data, axis=1)) # Minimum value along rows 
print(np.min(data, axis=0)) # Minimum value along rows   

[1 4]
[1 2 3]


In [24]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well   now calulate along the rows and columns
arr_1 = np.array([[1,2,3],[4,5,6],[10,20,30]])
print(np.min(arr_1))
print(np.max(arr_1))

1
30


In [25]:
# Index of min/max (argmin, argmax)
# here it give the index of minimum and maximum value in the array
arr = np.array([30, 10, 50, 20])
print(np.argmin(arr))          # index of smallest = 1
print(np.argmax(arr))          # index of largest = 2


1
2


In [26]:
# 2d array
data = np.array([[1, 2, 3], [0, 5, 6]])
print(np.argmin(data))          
print(np.argmax(data)) 

3
5


In [27]:
# it is not only for applicable for 1D array and 2D aarry but also applicable for higher dimensional array as well  now calulate along the rows and columns
arr_1 = np.array([[1,2,3],
                  [4,5,6],
                  [10,20,30]])
print(np.argmin(arr_1))
print(np.argmax(arr_1))

0
8


# Percentile & Quantile
Percentile tells you what value is at a given percentage position in sorted data. This is widely used in reporting (e.g. '90th percentile response time').

Quantile: it is a statistical measure that divides a sorted dataset or probability distribution into equal-sized, consecutive intervals

![alt image](https://i.sstatic.net/dTDGD.png)

In [28]:
# to calculate the percentiles of the data we can use the percentile function in numpy
arr = np.array([10,20,30,40,50,60,70,80,90,100])
# np.percentile(arrname, percentile_value)


print(np.percentile(arr, 25))   # 25th percentile (Q1)
print(np.percentile(arr, 50))   # 50th percentile = median
print(np.percentile(arr, 75))   # 75th percentile (Q3)
print(np.percentile(arr, 90))   # 90th percentile

32.5
55.0
77.5
91.0


In [29]:
# we can also calculate multiple percentiles at once by passing a list of percentiles to the function
q = np.percentile(arr, [25, 50, 75])
print(q)

[32.5 55.  77.5]


Calculating Interquartile Range 
<br>
<br>
IQR = Q3-Q1

In [30]:
q1 = np.percentile(arr, 25)
q2 = np.percentile(arr, 75)
IQR = q2 - q1
print(IQR)

45.0


Note: np.quantile() works exactly like np.percentile() but takes values between 0 and 1 instead of 0 and 100. For example, np.quantile(arr, 0.75) is same as np.percentile(arr, 75).
<br>
<br>
Let's got with some exaples

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
q1 = np.quantile(arr, 0.25)
print(q1)
# as you can see the quantile function is similar to percentile function but instead of passing the percentile value we are passing the quantile value which is between 0 and 1. so 0.25 is equivalent to 25th percentile, 0.5 is equivalent to 50th percentile and so on.

32.5


In [34]:
q1 = np.quantile(arr, 0.50)
print(q1)

55.0


In [35]:
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8])
marks       = np.array([40, 50, 55, 60, 70, 75, 85, 90])

corr_matrix = np.corrcoef(study_hours, marks)
print(corr_matrix)

[[1.         0.99655765]
 [0.99655765 1.        ]]


In [36]:
ages = np.array([22, 25, 27, 28, 30, 32, 35, 40, 45, 22, 25, 30, 28])

# Create 4 equal-width bins
counts, bin_edges = np.histogram(ages, bins=4)
print('Counts:    ', counts)
print('Bin edges: ', bin_edges)

Counts:     [5 5 1 2]
Bin edges:  [22.   27.75 33.5  39.25 45.  ]
